version: '3.4'

services:
  frontend:
    build:
      context: ui
    container_name: frontend
    ports:
      - "80:80"
      - "3000:3000"

  verifier:
    container_name: verifier
    image: docker.io/library/resbai_verifier:main-28f2207-dirty
    volumes:
    - ./temp:/app/app/static/
    # - ./temp/.git:/static_files/.git
    ports:
      - "8000:8000"
