version: '3.4'

services:
  verifier:
    container_name: verifier
    image: docker.io/library/resbai_verifier:main-f55bf51-dirty
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    # environment:
    #   - PYTHONPATH=/app
    ports:
      - "8000:8000"
    # network_mode: host
    # extra_hosts:
    #   - "seed:10.4.41.51"p